- hosts: nginx
  become: true
  tasks:
  - name: Add user for nginx
    user:
     name: nginx
     groups: sudo,docker
     shell: /bin/bash
     append: yes
     password: '$6$CGZ0zjUL.Xo/Wt$JbV2bbe7dLQWTJhxmFkrtp9Ng2RFwVcZ7VUEJ9a5A7I.X1G3egF.IhTs5GnWmV6Ap4ffHYkBNKUWZnV1rqo4v1'

- hosts: app
  become: true
  tasks:
  - name: Add user for app
    user:
     name: app
     groups: sudo,docker
     shell: /bin/bash
     append: yes
     password: '$6$CGZ0zjUL.Xo/Wt$JbV2bbe7dLQWTJhxmFkrtp9Ng2RFwVcZ7VUEJ9a5A7I.X1G3egF.IhTs5GnWmV6Ap4ffHYkBNKUWZnV1rqo4v1'

- hosts: jenkins
  become: true
  tasks:
  - name: Add user for jenkins
    user:
     name: jenkins
     groups: sudo,docker
     shell: /bin/bash
     append: yes
     password: '$6$CGZ0zjUL.Xo/Wt$JbV2bbe7dLQWTJhxmFkrtp9Ng2RFwVcZ7VUEJ9a5A7I.X1G3egF.IhTs5GnWmV6Ap4ffHYkBNKUWZnV1rqo4v1'

- hosts: monitoring
  become: true
  tasks:
  - name: Add user for monitoring
    user:
     name: monitoring
     groups: sudo,docker
     shell: /bin/bash
     append: yes
     password: '$6$CGZ0zjUL.Xo/Wt$JbV2bbe7dLQWTJhxmFkrtp9Ng2RFwVcZ7VUEJ9a5A7I.X1G3egF.IhTs5GnWmV6Ap4ffHYkBNKUWZnV1rqo4v1'

#Disable sign in without password

- hosts: all
  become: true
  tasks:
      - name: Change SSHD Config
        lineinfile:
          path: /etc/ssh/sshd_config
          regexp: '^PasswordAuthentication no'
          line: 'PasswordAuthentication yes'

      - name: Restart SSHD Service
        service:
          name: sshd
          state: restarted
          